ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.aitechapp.fun
REDIS_HOST: redis-{{ env }}.aitechapp.fun
MYSQL_HOST: mysql-{{ env }}.aitechapp.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.aitechapp.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.aitechapp.fun
USER_HOST: user.backend-alb-{{ env }}.aitechapp.fun
CART_HOST: cart.backend-alb-{{ env }}.aitechapp.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.aitechapp.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.aitechapp.fun
app_version: v3